### ISSUE TITLE
Overrides warnings not showing in problems pane

### ISSUE THREAD

**Issue by mcchong** [microsoft/vscode-eslint#1059]
I am migrating from a javascript project to typescript, and have set up a eslintrc.yml file with the following overrides:

```
  - files:
      - "*.ts"
      - "*.tsx"
    parser: "@typescript-eslint/parser"
    extends: 
      - plugin:@typescript-eslint/recommended
```

However, the warnings emitted by that overrides (which appear when building in the terminal) do not show in the problems pane.  I can't figure how to enable them so I think this is a bug.

Some more details:
- lint task is enabled
- I can see warnings from eslint from other rules in the "Problems" tab
- I can modify my eslintrc.yml file and disable and enable other rules
- The rules from the overrides item above are not visible in the problems tab, but visible when compiling other ways (e.g. running the build task).
