### ISSUE TITLE
`eslint.codeActionsOnSave.mode` silently overrides `eslint.codeActionsOnSave.rules`

### ISSUE THREAD

**Issue by laverdet** [microsoft/vscode-eslint#1388]
Using dbaeumer.vscode-eslint v2.2.2 w/ eslint v8.4.1

.vscode/settings.json:
```json
{
	"eslint.codeActionsOnSave.mode": "problems",
	"eslint.codeActionsOnSave.rules": [],
	"eslint.useESLintClass": true,
}
```

.eslintrc.yaml:
```yaml
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  no-multiple-empty-lines: [ warn, { max: 1, maxEOF: 0 } ]
  prefer-const: warn
```

package.json:
```json
{
  "name": "eslint-test",
  "version": "1.0.0",
  "dependencies": {
    "eslint": "^8.4.1"
  }
}
```

When saving a file all fixes are applied even though the rules are explicitly set to an empty array. It's ok that these two options are mutually exclusive but the interaction between them is surprising without any kind of runtime warning or documentation of this invariant.

Additionally the documentation around `eslint.codeActionsOnSave.rules` is a little confusing. It's stated "This setting is only honored if either ESLint version 8 or greater is used or ESLint version 7 is used and the setting eslint.useESLintClass is set to true." which I mentally parsed as: `version >= 8 || (version == 7.x && useESLintClass)`. Consider: "This setting requires ESLint 7 or higher and that the eslint.useESLintClass option is enabled".
