### ISSUE TITLE
monorep/recommended-requiring-type-checking/VS Code ESlint incorrect highlighting

### ISSUE THREAD

**Issue by what1s1ove** [microsoft/vscode-eslint#1619]
Hello there,

While using [recommended-requiring-type-checking](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/src/configs/recommended-requiring-type-checking.ts), the VSCode ESlint extension highlights all the rules that are included in this set of the rules.

<img width="731" alt="image" src="https://user-images.githubusercontent.com/42296182/224569048-9e94b27b-041a-490b-a35f-e7acd7c66e66.png">

But when using CLI ESlint, there will be no errors.

<img width="510" alt="image" src="https://user-images.githubusercontent.com/42296182/224569127-eb0e2796-2f83-4078-83b7-4b001fe894fe.png">

Interestingly, it highlights the rules that are used in `recommended-requiring-type-checking`. With all others, there is no such problem.

<img width="654" alt="image" src="https://user-images.githubusercontent.com/42296182/224569270-78db6076-b3c7-4fd9-92b4-58d67a594f86.png">
<img width="651" alt="image" src="https://user-images.githubusercontent.com/42296182/224569432-8c6e7d12-883c-4ccb-9af7-2fb6ddf16cb0.png">

ESlint config (root):

```yml
root: true

parserOptions:
  ecmaVersion: 2021
  sourceType: module
  project:
    - ./tsconfig.json
    - ./shared/tsconfig.json
    - ./backend/tsconfig.json
    - ./frontend/tsconfig.json

settings:
  typescript: true
  node: true

extends:
  - eslint:recommended
  - plugin:import/recommended
  - plugin:import/typescript
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - plugin:@typescript-eslint/strict
  - plugin:unicorn/recommended
  - plugin:sonarjs/recommended

plugins:
  - simple-import-sort
```

ESlint config (frontend):

```yml
env:
  browser: true

settings:
  react:
    version: 'detect'

parserOptions:
  project:
    - ./tsconfig.json

extends:
  - ../.eslintrc.yml
  - plugin:react/recommended
  - plugin:react/jsx-runtime
  - plugin:react-hooks/recommended
  - plugin:jsx-a11y/recommended
```

All teammates use different operating systems (Windows, Linux, MacOS). Everyone has this problem.

Tried to find similar issues among other issues but could not find anything similar. This is an open-source educational project. Any recommendations would be grateful 🙏

https://github.com/BinaryStudioAcademy/bsa-winter-2022-2023-simpleland
