### ISSUE TITLE
NodeJS built-in package import throw an error with this plugin

### ISSUE THREAD

**Issue by pebie** [microsoft/vscode-eslint#1633]
**Eslint configuration :**

```yaml
root: true
parserOptions:
  ecmaVersion: 13
  sourceType: module
env:
  node: true
  es6: true
  mocha: true
plugins:
  - 'import'
extends:
  - 'eslint:recommended'
  - 'plugin:prettier/recommended'
  - 'plugin:import/errors'
  - 'plugin:import/warnings'
  - 'plugin:security/recommended'
settings:
  'import/internal-regex': '^\.\.?/'
rules:
  'no-console': 'off'
  'no-duplicate-imports': 'error'
  'no-return-await': 'error'
  'no-unneeded-ternary': 'error'
  'no-unused-vars': ['error', {ignoreRestSiblings: true, args: 'none'}]
  'prefer-object-spread': 'error'
  'require-await': 'off'
  'import/order':
    [
      'error',
      {
        groups: ['builtin', 'external', ['internal', 'parent', 'sibling', 'index'], 'unknown'],
        'newlines-between': 'always',
        alphabetize: {order: 'asc', caseInsensitive: true},
      },
    ]
```

**My ESM module looks like this** 

```javascript
import test from 'node:test'
// Whatever...
```

**Run CLI eslint command :** 
yarn
```shell
yarn eslint ./
```
This command run eslint against all of my *.js files and does not cause an error

**With vscode-eslint plugin**
```shell
Unable to resolve path to module 'node:test'.
```

In the plugin configuration, I'm trying to figure out what's wrong. I let default setup. 

**Node version :** 18.16
**Eslint informations :** 
```json
        "eslint": "8.31.0",
        "eslint-config-prettier": "8.6.0",
        "eslint-plugin-import": "2.27.5",
        "eslint-plugin-prettier": "4.2.1",
        "eslint-plugin-security": "1.5.0",
```

**Additionnal info about package.json** : I use `"type": "module"`

Thanks for your help !
