### ISSUE TITLE
ignoreEOLComments has additional properties

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode-eslint#299]
_From @xovel on September 17, 2017 16:35_

- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:23.027Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-color|ans|0.4.5
vscode-eslint|dba|1.3.1
githistory|don|0.2.3
beautify|Hoo|1.1.1
vscode-regexp-preivew|le0|0.0.3
sublime-keybindings|ms-|2.9.1
debugger-for-chrome|msj|3.3.0
material-icon-theme|PKi|2.2.1
java|red|0.10.0

---

Steps to Reproduce:

1. Open a front-end project
2. Warning come...

Warning text:

> e:\svn\drs-frontend\.eslintrc.yml: Configuration for rule "no-multi-spaces" is invalid: Value "data["0"].ignoreEOLComments" has additional properties.

Reproduces without extensions: Yes

***************

My .eslintrc.yml:

```yml
...
  no-magic-numbers: 0

  # 禁止多个空格
  # no-multi-spaces: 0
  no-multi-spaces:
    - 2
    -
      ignoreEOLComments: true
      exceptions:
        Property: true
        VariableDeclarator: true
        ImportDeclaration: true

  # 禁止多行字符串
  no-multi-str: 1

...
```

_Copied from original issue: Microsoft/vscode#34544_
