### ISSUE TITLE
autofix doesn't work when working with typescript-eslint

### ISSUE THREAD

**Issue by zzzgit** [Microsoft/vscode-eslint#663]
In a typescript project, I use `typescript-eslint` to plugin into eslint.
This is my config: 
```yml
env:
  node: true
  commonjs: true
  es6: true
extends: 'eslint:recommended'
parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
parserOptions:
  sourceType: module
  ecmaVersion: 2017
rules:
  indent:
    - error
    - tab
  linebreak-style:
    - off
  quotes:
    - off
  semi:
    - error
    - never
  no-useless-escape:
    - warn
  no-console:
    - off
  no-var:
    - error
```
And then I found there will be no autofix bulb in vs-code.
Maybe this plugin can't work well with `typescript-eslint`
